#routing
#discovery feature
#    spring.cloud.gateway.discovery.locator.enabled=true
#    spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#----------------------------------------------------
#    spring.cloud.gateway.routes[0].id=user
#    spring.cloud.gateway.routes[0].uri=lb://user-ms
#    spring.cloud.gateway.routes[0].predicates[0]=Path=/user/status/check
#    spring.cloud.gateway.routes[0].predicates[1]=Method=GET

hystrix:
    command:
        falllbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream

spring:
    cloud:
        gateway:
            routes:
                - id: order-service
                  uri: lb://Order-Service
                  predicates:
                      - Path=/order/**
#                  filters:
#                      - name: CircuitBreaker
#                        args:
#                            name: order-service
#                            fallbackUri: forward:/orderServiceFallback
                - id: payment-service
                  uri: lb://payment-service
                  predicates:
                      - Path=/payment/**
#                  filters:
#                      - name: CircuitBreaker
#                        args:
#                            name: payment
#                            fallbackUri: forward:/paymentServiceFallback
